account/urls.py
from django.urls import path 
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logoutView, name='logout'),
]

product/urls.py
from django.urls import path
from . import views


app_name = 'product'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('add/', views.addView.as_view(), name='add'),
    path('detail/<int:pk>/', views.ProductDetail.as_view(), name='detail'),
    path('update/<int:pk>/', views.ProductEdit.as_view(), name='update'),
    path('card/', views.CardView.as_view(), name='card'),
    path('order/<int:pk>', views.OrderView.as_view(), name='order'),
]

handler403 = views.permission_denied_view

tiles/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='product')),
    path('accounts/', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

product/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/')

    def __str__(self):
        return self.name
    
class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return str(self.customer.username)
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
 
        return total

# Order Item model
class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order,  on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=1)
    order_added = models.DateTimeField(auto_now_add=True)
    is_order = models.BooleanField(default=False)

    def __str__(self):
        return str(self.order)+ " => "+self.product.name
    
    @property
    def get_total(self):
        total = self.quantity * self.product.price
        return total

# Shipping model
class Shipping(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    address = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

account/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User,Group
from django.contrib.auth import authenticate,logout,login
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.

def register(request):
    if request.user.is_authenticated:
        return redirect('product:index')
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        check_username = User.objects.filter(username=username)

        if check_username:
            return render(request,'register.html', {'error': 'Username already exists'})
        
        user = User.objects.create_user(username=username, password=password)
        user.is_active = True
        # add the user to a group
        group_name = 'user'
        group, created = Group.objects.get_or_create(name=group_name)
        if created:
            pass
        user.groups.add(group)
        user.save()
        return redirect('account:login')
    else:
        return render(request,'register.html')


def loginView(request):
    if request.user.is_authenticated:
        return redirect('product:index')
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        print(user)
        # return render(request,'login.html')
        if user is not None:
            login(request,user)
            return redirect('product:index')
        else:
            return render(request,'login.html', {'error': 'Invalid username or password'})
    else:
        return render(request,'login.html')

@login_required
def logoutView(request):
    logout(request)
    return redirect('account:login')

product/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy 
from django.views.generic import CreateView, TemplateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from product.models import OrderItem, Product, Order
# Create your views here.

class HomeView(TemplateView):
    template_name = 'index.html'

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            order_id = self.request.POST.get('order_id')
            product = Product.objects.get(pk=order_id)
            user = self.request.user
            order_item = OrderItem.objects.create(user=user, product=product)
            order_item.save()
            return redirect('product:index')
        else:
            return redirect('account:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["products"] = Product.objects.all()
        return context
    

class addView(LoginRequiredMixin,CreateView):
    model  = Product
    fields = ['name', 'price', 'image']
    success_url = reverse_lazy('product:index')


class ProductDetail(DetailView):
    model = Product
    context_object_name = 'product'


class ProductEdit(LoginRequiredMixin,UpdateView):
    model = Product
    fields = ['name', 'price', 'image']
    
    def get_success_url(self):
        return reverse_lazy('product:detail', kwargs={'pk': self.object.pk})


class CardView(LoginRequiredMixin,TemplateView):
    template_name = 'card.html'
    model = Order

    def product(self, *args, **kwargs):
        products = OrderItem.objects.filter(user=self.request.user).filter(is_order=False)
        total = sum([item.get_total for item in products])
        return total
    

    def post(self, request, *args, **kwargs):
        user = self.request.user
        order = Order.objects.create(customer=user)
        order.save()
        products = OrderItem.objects.filter(user=self.request.user).filter(is_order=False)
        products.update(is_order=True)
        return redirect("product:order", pk=order.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["products"] = OrderItem.objects.filter(user=self.request.user).filter(is_order=False)
        return context

# class PlaceOrder(LoginRequiredMixin,TemplateView):
    
class OrderView(LoginRequiredMixin,DetailView):
    template_name = 'order.html'
    model = Order
    context_object_name = 'order'

    
def permission_denied_view(request, exception):
    return render(request, 'permission_denied.html', status=403)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
  <style>
    .card.shadow-sm img {
        height: 254px;
        object-fit: cover;
    }
  </style>
  </head>
  <body>
    

  <div class="container">
    <nav class="navbar navbar-expand-md">
        <div class="container">
          <a class="navbar-brand" href="/">Logo</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
            
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'product:card' %}">Card</a>
              </li>
             
              {% if perms.product.view_product %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'product:add' %}">Add </a>
                </li>
              {% endif %}
                
            </ul>
            <div class="d-flex" role="login">

              {% if user.is_authenticated %}
                <p class="p-1">{{ user.username }}</p>
                <a class="btn btn-outline-success" href="{% url 'account:logout' %}">Logout</a>
              {% else %}
                <a class="btn btn-outline-success" href="{% url 'account:login' %}">Login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
  </div>
 
 {% block main %}
    
 {% endblock main %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
  </body>
</html>

templates/card.html
{% extends 'base.html' %}
{% block main %}

    <div class="container">
        <ul class="list-group">
            
            {% for product in products %}
                <li class="list-group-item">{{ product.product }}  price: {{ product.get_total  }}</li>
            {% endfor %}
          </ul>
          
          {% if products|length > 0 %}
            <form method="POST">
                {% csrf_token %}
                <input type="submit" value="Place order">
            </form>
          {% else %}
            <p>No products found.</p>
          {% endif %}
            
    </div>

{% endblock main %}

templates/index.html
{% extends 'base.html' %}
    

{% block main %}
  <div class="container mt-5">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
       {% for product in products %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ product.image.url }}" alt="">
            <div class="card-body">
              <p class="card-text"> {{ product.name }} | Price: {{ product.price }} </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'product:detail' product.id %}" type="button" class="btn btn-sm btn-outline-secondary">View</a> 
                  
                  {% if product.orderitem_set.all %}
                  {% for order_item in product.orderitem_set.all %}
                    {% if order_item.order %}
                      <button class="btn btn-sm btn-outline-secondary" disabled>Already added</button>
                    {% else %}
                      <form method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="order_id" value="{{product.id}}">
                        <button class="btn btn-sm btn-outline-secondary" type="submit">Add to card</button>
                      </form>
                    {% endif %}
                  {% endfor %}
                {% else %}
                  <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="order_id" value="{{product.id}}">
                    <button class="btn btn-sm btn-outline-secondary" type="submit">Add to card</button>
                  </form>
                {% endif %}
                

                  {% if perms.product.change_product %}
                    <a href="{% url 'product:update' product.id %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
  </div>

{% endblock main %}

templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
  </head>
  <body>
    
    
   <div class="container">
    <div class="col-md-4 mt-2">
        
        {% if error %}
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ error }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endif %}
      </div>
    <form method="POST">
        {% csrf_token %}
        <div class="col-md-4">
            <label for="validationDefaultUsername" class="form-label">Username</label>
            <div class="input-group">
              <input name="username" type="text" class="form-control" id="validationDefaultUsername" aria-describedby="inputGroupPrepend2" required>
            </div>
          </div>
  
          <div class="col-md-4">
            <label for="validationDefaultPassword" class="form-label">Password</label>
            <div class="input-group">
              <input name="password" type="password" class="form-control" id="validationDefaultPassword" aria-describedby="inputGroupPrepend" required>
            </div>
          </div>
  
          <div class="col-12 mt-3">
            <button class="btn btn-primary" type="submit">Login</button>
          </div>
    </form>

    <p class="mt-3"> <a href="{% url 'account:register' %}">Register</a> for a new account </p>
   </div>


    
    
    
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>

  </body>
</html>

templates/order.html
{% extends 'base.html' %}


{% block main %}
   <div class="container">
        {{ order.orderitem_set.all }}
   </div>
{% endblock main %}
    

templates/permission_denied.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <p>You don't have permission to access this page</p>
    </body>
</html>

templates/product/product_detail.html
{% extends 'base.html' %}

{% block main %}

  <div class="container mt-5">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ product.image.url }}" alt="">
            <div class="card-body">
              <p class="card-text"> {{ product.name }} | Price: {{ product.price }} </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  {% if user.is_authenticated and user.is_superuser %}
                    <a href="{% url 'product:update' product.id %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>

{% endblock main %}

templates/product/product_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    
<form method="POST" enctype="multipart/form-data">
 
    <!-- Security token -->
    {% csrf_token %}
 
    <!-- Using the formset -->
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>
    
</body>
</html>

templates/register.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
  </head>
  <body>
    

    <div class="container">
        <div class="col-md-8 mt-2">
          {% if error %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              {{ error }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endif %}
        </div>
      <form class="row g-3 mt-3" method="POST">
        {% csrf_token %}
        <div class="col-md-4">
          <label for="validationDefaultUsername" class="form-label">Username</label>
          <div class="input-group">
            <input name="username" type="text" class="form-control" id="validationDefaultUsername" aria-describedby="inputGroupPrepend2" required>
          </div>
        </div>

        <div class="col-md-4">
          <label for="validationDefaultPassword" class="form-label">Password</label>
          <div class="input-group">
            <input name="password" type="password" class="form-control" id="validationDefaultPassword" aria-describedby="inputGroupPrepend" required>
          </div>
        </div>

        <div class="col-12">
          <button class="btn btn-primary" type="submit">Submit</button>
        </div>
      </form>
      <p class="mt-3"> <a href="{% url 'account:login' %}">Login</a> already have an account </p>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
  </body>
</html>